server:
  port: 9530

spring:
  application:
    name: kung-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/busiOrder?characterEncoding=utf-8&&serverTimezone=GMT%2B8
    username: root
    password: hdY19900822
dubbo:
  registry:
    address: spring-cloud://localhost
  application:
    qos-enable: false
  cloud:
    subscribed-services: service-receive,service-query

