server:
  port: 9530

spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  registry:
    address: spring-cloud://localhost
  application:
    qos-enable: false
  cloud:
    subscribed-services: service-receive

